using System;
using CommunityToolkit.Mvvm.ComponentModel;
using SquareClickerPointer.EventArgs;
using SquareClickerPointer.EventBuses;

namespace SquareClickerPointer.ViewModels;

// ═══════════════════════════════════════════════════════════════════════════════
//  TriangleAlphaDataViewModel  —  the subscriber in the pub/sub pattern
// ═══════════════════════════════════════════════════════════════════════════════
//
//  ROLE IN THE SYSTEM
//  ──────────────────
//  This ViewModel is a pure CONSUMER.  It does not call any methods on
//  PointControlViewModel, does not hold a reference to it, and does not even
//  know its class name.  All it knows is that somewhere in the process a
//  DotReleasedEventArgs payload will be raised on DotPositionEventBus.
//
//  WHY THAT MATTERS
//  ────────────────
//  Imagine in six months you replace PointControlView with a joystick controller.
//  As long as the joystick code calls DotPositionEventBus.Publish(...) when input
//  is committed, this class continues to work without a single edit.  Neither
//  side depends on the other's implementation — only on the shared bus instance
//  and the DotReleasedEventArgs payload contract.
//
//  DATA FLOW
//  ─────────
//
//   DotPositionEventBus
//         │   DotReleasedEventArgs(X, Y)
//         ▼
//   OnDotReleased(sender, e)
//         │
//         ├─ LastX, LastY  ←  raw values echoed for the "Received" display row
//         ├─ Distance      ←  √(X² + Y²)
//         ├─ AngleDegrees  ←  atan2(Y, X) × (180/π)
//         ├─ TriangleArea  ←  ½ · X · Y
//         ├─ Perimeter     ←  X + Y + Distance
//         └─ HasData       ←  flipped to true so the View hides the placeholder
//                              │
//                              ▼ (INotifyPropertyChanged)
//                       TriangleAlphaDataView  (XAML bindings refresh automatically)
//
//  WHY CALCULATIONS LIVE HERE (NOT IN THE VIEW)
//  ─────────────────────────────────────────────
//  The ViewModel is responsible for transforming raw data into display-ready values.
//  If atan2() lived in a XAML value converter or in code-behind, you could not test
//  the math without rendering a window.  Here you can write:
//
//      var bus = new DotPositionEventBus();
//      var vm  = new TriangleAlphaDataViewModel(bus);
//      bus.Publish(this, new DotReleasedEventArgs(3.0, 4.0));
//      Assert.Equal(5.0, vm.Distance, precision: 10);
//
//  No UI involved.

/// <summary>
/// ViewModel for the TriangleAlphaData user control.
/// Subscribes to <see cref="DotPositionEventBus.DotReleased"/> and exposes
/// computed geometry values that the View displays via data-binding.
/// Implements <see cref="IDisposable"/> so the subscription can be released
/// when the ViewModel is no longer needed (preventing memory leaks).
/// </summary>
public partial class TriangleAlphaDataViewModel : ViewModelBase, IDisposable
{
    // ── DotPositionEventBus — injected via DI ────────────────────────────────────
    //
    // Same injection pattern as PointControlViewModel.  The DI container provides
    // the *same* DotPositionEventBus singleton to both ViewModels — this is the
    // key insight:
    //
    //   PointControlViewModel        →  publishes on bus instance A
    //   TriangleAlphaDataViewModel   →  subscribes on bus instance A
    //
    // If two different bus instances were used, the event would never arrive.
    // That is why the bus is registered as a SINGLETON in App.axaml.cs — the
    // container ensures both ViewModels share one instance.
    //
    private readonly DotPositionEventBus _dotBus;

    // ── Display properties ────────────────────────────────────────────────────────
    //
    // All double properties are generated by [ObservableProperty] which creates the
    // full INotifyPropertyChanged plumbing.  When OnDotReleased sets Distance = 7.07,
    // the source generator fires PropertyChanged("Distance") and the XAML text
    // binding in TriangleAlphaDataView.axaml updates the screen automatically.
    // No "refresh" method needed — the binding system handles it.

    /// <summary>X coordinate received from the last DotReleased event.</summary>
    [ObservableProperty] private double _lastX;

    /// <summary>Y coordinate received from the last DotReleased event.</summary>
    [ObservableProperty] private double _lastY;

    /// <summary>
    /// Euclidean distance from the origin (0,0) to point (X,Y).
    /// This is the hypotenuse of the right triangle formed by (0,0)→(X,0)→(X,Y).
    /// Formula: √(X² + Y²)
    /// </summary>
    [ObservableProperty] private double _distance;

    /// <summary>
    /// Angle α (alpha) in degrees from the positive X-axis to the vector (X,Y).
    /// Formula: atan2(Y, X) × (180 / π)
    /// Range: −180° to +180°.
    ///   (1, 0) → 0°  |  (0, 1) → 90°  |  (0, 0) → 0° (undefined at origin)
    /// </summary>
    [ObservableProperty] private double _angleDegrees;

    /// <summary>
    /// Area of the right triangle formed by origin (0,0), (X,0), and (X,Y).
    /// Formula: ½ × base × height = ½ × X × Y
    /// </summary>
    [ObservableProperty] private double _triangleArea;

    /// <summary>
    /// Perimeter of that same right triangle: both legs plus the hypotenuse.
    /// Formula: X + Y + √(X² + Y²)
    /// </summary>
    [ObservableProperty] private double _perimeter;

    /// <summary>
    /// False until the first DotReleased event arrives.
    /// The View shows a "waiting" placeholder while this is false, then switches
    /// to the results panel when it becomes true.
    /// </summary>
    [ObservableProperty] private bool _hasData;

    // ── Constructor ───────────────────────────────────────────────────────────────

    /// <param name="dotBus">
    /// The shared DotPositionEventBus singleton, provided by the DI container.
    /// Both this class and PointControlViewModel receive the same instance, which
    /// is what makes the published events arrive here.
    /// </param>
    public TriangleAlphaDataViewModel(DotPositionEventBus dotBus)
    {
        _dotBus = dotBus;

        // ── Subscribe to DotReleased ─────────────────────────────────────────────
        //
        // Subscribe wires our OnDotReleased method into the bus's event.  Whenever
        // a publisher calls _dotBus.Publish(...), the bus invokes every attached
        // handler — including OnDotReleased here.
        //
        // WHY USE A METHOD GROUP (OnDotReleased) RATHER THAN A LAMBDA:
        //   We must be able to UNSUBSCRIBE in Dispose().  An anonymous lambda
        //   captured at construction time would be a different delegate instance
        //   each time we tried to remove it — Unsubscribe would silently do
        //   nothing, leaving a dangling subscription.  The method-group form
        //   produces an equal delegate on Subscribe and Unsubscribe so the
        //   removal works.
        _dotBus.Subscribe(OnDotReleased);
    }

    // ── IDisposable ───────────────────────────────────────────────────────────────
    //
    // The bus holds a strong reference to this ViewModel through the subscription
    // delegate.  If we never unsubscribe, the bus keeps this VM alive forever —
    // a memory leak.  Calling Dispose() (typically when the owning View is
    // unloaded, or in tests when tearing down) breaks that reference.

    public void Dispose()
    {
        _dotBus.Unsubscribe(OnDotReleased);
    }

    // ── Event handler ─────────────────────────────────────────────────────────────

    /// <summary>
    /// Called by the bus on the publishing thread whenever PointControlViewModel
    /// raises the DotReleased event (i.e., user releases the dot).
    ///
    /// All property assignments here raise INotifyPropertyChanged automatically
    /// (via [ObservableProperty]), so XAML bindings update without any manual work.
    /// </summary>
    private void OnDotReleased(object? sender, DotReleasedEventArgs e)
    {
        // Echo the raw input values so the View can display "Received X / Y".
        LastX = e.X;
        LastY = e.Y;

        // ── Distance: Pythagorean theorem ─────────────────────────────────────────
        // √(X² + Y²) — the straight-line length from origin to the point.
        // If the dot is at (3, 4) the distance is √(9+16) = √25 = 5.
        Distance = Math.Sqrt(e.X * e.X + e.Y * e.Y);

        // ── Alpha angle: atan2 ────────────────────────────────────────────────────
        // Math.Atan2(y, x) returns the angle of the 2-D vector in RADIANS (−π to +π).
        // We multiply by (180/π) to convert to degrees for human readability.
        // atan2 is preferred over atan(y/x) because it handles all four quadrants
        // and does not divide-by-zero when X = 0.
        AngleDegrees = Math.Atan2(e.Y, e.X) * (180.0 / Math.PI);

        // ── Triangle area: ½ · base · height ─────────────────────────────────────
        // The right triangle has base = X (along the X-axis) and height = Y.
        // Area = ½ × X × Y.
        TriangleArea = 0.5 * e.X * e.Y;

        // ── Perimeter: two legs + hypotenuse ─────────────────────────────────────
        // The two legs are X (horizontal) and Y (vertical).
        // The hypotenuse is Distance, which we already computed above.
        Perimeter = e.X + e.Y + Distance;

        // Switch the View from "waiting" placeholder to the results panel.
        HasData = true;
    }
}
