using System;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Messaging;
using SquareClickerPointer.Messages;

namespace SquareClickerPointer.ViewModels;

// ═══════════════════════════════════════════════════════════════════════════════
//  TriangleAlphaDataViewModel  —  the subscriber in the pub/sub pattern
// ═══════════════════════════════════════════════════════════════════════════════
//
//  ROLE IN THE SYSTEM
//  ──────────────────
//  This ViewModel is a pure CONSUMER.  It does not call any methods on
//  PointControlViewModel, does not hold a reference to it, and does not even
//  know its class name.  All it knows is that somewhere in the process a
//  DotReleasedMessage record will arrive via IMessenger.
//
//  WHY THAT MATTERS
//  ────────────────
//  Imagine in six months you replace PointControlView with a joystick controller.
//  As long as the joystick code sends a DotReleasedMessage when input is committed,
//  this class continues to work without a single edit.  Neither side depends on the
//  other's implementation — only on the shared message contract.
//
//  That contract is defined in Messages/DotReleasedMessage.cs.
//
//  DATA FLOW
//  ─────────
//
//   WeakReferenceMessenger.Default
//         │   DotReleasedMessage(X, Y)
//         ▼
//   OnDotReleased(message)
//         │
//         ├─ LastX, LastY  ←  raw values echoed for the "Received" display row
//         ├─ Distance      ←  √(X² + Y²)
//         ├─ AngleDegrees  ←  atan2(Y, X) × (180/π)
//         ├─ TriangleArea  ←  ½ · X · Y
//         ├─ Perimeter     ←  X + Y + Distance
//         └─ HasData       ←  flipped to true so the View hides the placeholder
//                              │
//                              ▼ (INotifyPropertyChanged)
//                       TriangleAlphaDataView  (XAML bindings refresh automatically)
//
//  WHY CALCULATIONS LIVE HERE (NOT IN THE VIEW)
//  ─────────────────────────────────────────────
//  The ViewModel is responsible for transforming raw data into display-ready values.
//  If atan2() lived in a XAML value converter or in code-behind, you could not test
//  the math without rendering a window.  Here you can write:
//
//      var vm = new TriangleAlphaDataViewModel(new WeakReferenceMessenger());
//      vm.Messenger.Send(new DotReleasedMessage(3.0, 4.0));
//      Assert.Equal(5.0, vm.Distance, precision: 10);
//      Assert.Equal(90.0 - Math.Atan(3.0/4.0)*180/Math.PI, vm.AngleDegrees, ...);
//
//  No UI involved.

/// <summary>
/// ViewModel for the TriangleAlphaData user control.
/// Subscribes to <see cref="DotReleasedMessage"/> and exposes computed geometry
/// values that the View displays via data-binding.
/// </summary>
public partial class TriangleAlphaDataViewModel : ViewModelBase
{
    // ── IMessenger — injected via DI ──────────────────────────────────────────────
    //
    // Same injection pattern as PointControlViewModel.  The DI container provides
    // the *same* IMessenger singleton to both ViewModels — this is the key insight:
    //
    //   PointControlViewModel  →  sends on IMessenger instance A
    //   TriangleAlphaDataViewModel  →  listens on IMessenger instance A
    //
    // If two different IMessenger instances were used, the message would never arrive.
    // That is why both are registered as SINGLETONS in App.axaml.cs — the container
    // ensures they share one instance.
    //
    private readonly IMessenger _messenger;

    // ── Display properties ────────────────────────────────────────────────────────
    //
    // All double properties are generated by [ObservableProperty] which creates the
    // full INotifyPropertyChanged plumbing.  When OnDotReleased sets Distance = 7.07,
    // the messenger fires PropertyChanged("Distance") and the XAML text binding in
    // TriangleAlphaDataView.axaml updates the screen automatically.  No "refresh"
    // method needed — the binding system handles it.

    /// <summary>X coordinate received from the last DotReleasedMessage.</summary>
    [ObservableProperty] private double _lastX;

    /// <summary>Y coordinate received from the last DotReleasedMessage.</summary>
    [ObservableProperty] private double _lastY;

    /// <summary>
    /// Euclidean distance from the origin (0,0) to point (X,Y).
    /// This is the hypotenuse of the right triangle formed by (0,0)→(X,0)→(X,Y).
    /// Formula: √(X² + Y²)
    /// </summary>
    [ObservableProperty] private double _distance;

    /// <summary>
    /// Angle α (alpha) in degrees from the positive X-axis to the vector (X,Y).
    /// Formula: atan2(Y, X) × (180 / π)
    /// Range: −180° to +180°.
    ///   (1, 0) → 0°  |  (0, 1) → 90°  |  (0, 0) → 0° (undefined at origin)
    /// </summary>
    [ObservableProperty] private double _angleDegrees;

    /// <summary>
    /// Area of the right triangle formed by origin (0,0), (X,0), and (X,Y).
    /// Formula: ½ × base × height = ½ × X × Y
    /// </summary>
    [ObservableProperty] private double _triangleArea;

    /// <summary>
    /// Perimeter of that same right triangle: both legs plus the hypotenuse.
    /// Formula: X + Y + √(X² + Y²)
    /// </summary>
    [ObservableProperty] private double _perimeter;

    /// <summary>
    /// False until the first DotReleasedMessage arrives.
    /// The View shows a "waiting" placeholder while this is false, then switches
    /// to the results panel when it becomes true.
    /// </summary>
    [ObservableProperty] private bool _hasData;

    // ── Constructor ───────────────────────────────────────────────────────────────

    /// <param name="messenger">
    /// The shared IMessenger singleton, provided by the DI container.
    /// Both this class and PointControlViewModel receive the same instance, which
    /// is what makes the published messages arrive here.
    /// </param>
    public TriangleAlphaDataViewModel(IMessenger messenger)
    {
        _messenger = messenger;

        // ── Subscribe to DotReleasedMessage ───────────────────────────────────────
        //
        // IMessenger.Register<TMessage>(recipient, handler) tells the bus:
        // "whenever someone sends a DotReleasedMessage, call handler with it."
        //
        // WHY WeakReferenceMessenger (not StrongReferenceMessenger):
        //
        //   WeakReferenceMessenger holds only a WEAK reference to the recipient ('this').
        //   If this ViewModel is garbage-collected (e.g. the user closes the control),
        //   the messenger will not keep it alive.  With a StrongReferenceMessenger,
        //   a registered-but-destroyed ViewModel would be kept in memory forever —
        //   a classic memory leak.
        //
        // WHY the lambda uses (recipient, message) rather than capturing 'this':
        //
        //   If we wrote:  _messenger.Register<DotReleasedMessage>(this, (_, msg) => OnDotReleased(msg))
        //   the closure `() => OnDotReleased(msg)` holds a strong reference to 'this'
        //   through the captured delegate — defeating the weak reference mechanism.
        //
        //   The (recipient, message) signature is CommunityToolkit.Mvvm's solution:
        //   'recipient' is the typed weak target.  The lambda receives it as a typed
        //   parameter instead of capturing it in a closure.  The messenger stores the
        //   recipient weakly; the delegate itself holds no strong reference.
        //
        _messenger.Register<TriangleAlphaDataViewModel, DotReleasedMessage>(this, (recipient, message) =>
        {
            recipient.OnDotReleased(message);
        });
    }

    // ── Message handler ───────────────────────────────────────────────────────────

    /// <summary>
    /// Called by the messenger on the UI thread whenever PointControlViewModel
    /// publishes a <see cref="DotReleasedMessage"/> (i.e., user releases the dot).
    ///
    /// All property assignments here raise INotifyPropertyChanged automatically
    /// (via [ObservableProperty]), so XAML bindings update without any manual work.
    /// </summary>
    private void OnDotReleased(DotReleasedMessage message)
    {
        // Echo the raw input values so the View can display "Received X / Y".
        LastX = message.X;
        LastY = message.Y;

        // ── Distance: Pythagorean theorem ─────────────────────────────────────────
        // √(X² + Y²) — the straight-line length from origin to the point.
        // If the dot is at (3, 4) the distance is √(9+16) = √25 = 5.
        Distance = Math.Sqrt(message.X * message.X + message.Y * message.Y);

        // ── Alpha angle: atan2 ────────────────────────────────────────────────────
        // Math.Atan2(y, x) returns the angle of the 2-D vector in RADIANS (−π to +π).
        // We multiply by (180/π) to convert to degrees for human readability.
        // atan2 is preferred over atan(y/x) because it handles all four quadrants
        // and does not divide-by-zero when X = 0.
        AngleDegrees = Math.Atan2(message.Y, message.X) * (180.0 / Math.PI);

        // ── Triangle area: ½ · base · height ─────────────────────────────────────
        // The right triangle has base = X (along the X-axis) and height = Y.
        // Area = ½ × X × Y.
        TriangleArea = 0.5 * message.X * message.Y;

        // ── Perimeter: two legs + hypotenuse ─────────────────────────────────────
        // The two legs are X (horizontal) and Y (vertical).
        // The hypotenuse is Distance, which we already computed above.
        Perimeter = message.X + message.Y + Distance;

        // Switch the View from "waiting" placeholder to the results panel.
        HasData = true;
    }
}
